"use strict";

module.exports = {
    Administrators               : require('./administrators'),
    AdministratorAttributes      : require('./administratorAttributes'),
    AdministratorPermissions     : require('./administratorPermissions'),
    AdministratorTokens          : require('./administratorTokens'),
    Attributes                   : require('./attributes'),
    AttributeTypes               : require('./attributeTypes'),
    CardTypes                    : require('./cardTypes'),
    Companies                    : require('./companies'),
    CompanyWallets               : require('./companyWallets'),
    CompanyStatuses              : require('./companyStatuses'),
    CompanyAttributes            : require('./companyAttributes'),
    Groups                       : require('./groups'),
    Operators                    : require('./operators'),
    OperationTransactions        : require('./operationTransactions'),
    OperationTransactionStatuses : require('./operationTransactionStatuses'),
    Permissions                  : require('./permissions'),
    Persons                      : require('./persons'),
    PersonCards                  : require('./personCards'),
    PersonGroups                 : require('./personGroups'),
    PersonAttributes             : require('./personAttributes'),
    Settings                     : require('./settings'),
    Users                        : require('./users'),
    UserTokens                   : require('./userTokens'),
    UserStatuses                 : require('./userStatuses'),
    UserCompanies                : require('./userCompanies'),
    UserAttributes               : require('./userAttributes'),
    UserPermissions              : require('./userPermissions'),
    RechargeTransactions         : require('./rechargeTransactions'),
    RechargeTransactionStatuses  : require('./rechargeTransactionStatuses')
};
